# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccfad200681f151133a08d17c751e73ed9a35e125d53199cc56768c80cad2087a6d0c185edd8c16ca7559a8b547e9c218725609908e053026b18f39c871c624f

test:
  secret_key_base: 2af935c55e99e431d4ecba2e964054d77f445c1d2bda39b869c4485f84e995ef0b4be713ccb8f32d2055b070709e0754010984824d80b4644bf750509305e780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
